config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get '_up' => 'rails/health#show', as: :rails_health_check

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resource :collection, only: %i[show]
  resource :session, only: %i[new create destroy]
  resource :user

  namespace :pokemon do
    resources :cards, only: %i[index show]
  end

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_token :confirmation_token
  has_secure_password

  validates :email,
            format: { with: URI::MailTo::EMAIL_REGEXP },
            presence: true,
            uniqueness: { case_sensitive: false }

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  has_many :cards, dependent: :destroy_async, extend: HasManyCards
  has_many :decks, dependent: :destroy_async

  class << self
    def find_and_authenticate_by!(email:, password:)
      find_by!(email:).authenticate!(password)
    rescue ActiveRecord::RecordNotFound
      raise Deckshare::Errors::AuthenticationError
    end
  end

  def authenticate!(password)
    authenticate(password) or raise Deckshare::Errors::AuthenticationError
  end

  def to_s
    username
  end
end

app/models/user/card.rb
# frozen_string_literal: true

class User
  class Card < ApplicationRecord
    attr_readonly :user, :card

    belongs_to :user
    belongs_to :card, polymorphic: true

    validates :card_type, inclusion: { in: %w[Pokemon::Card] }
    validates :quantity, numericality: { greater_than: 0 }

    scope :pokemon, -> { where(card_type: 'Pokemon::Card') }
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include Authentication

  before_action :authenticate_user!, except: %i[new create]
  before_action :unauthenticate_user!, only: %i[new create]

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(create_params)
    @user.save!

    redirect_to action: :show
  rescue ActiveRecord::RecordInvalid
    render action: :new, status: :unprocessable_entity
  end

  def update
    redirect_to action: :show
  end

  def destroy
    redirect_to action: :new
  end

  private

  def create_params
    params.require(:user).permit(*%i[username email password password_confirmation])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, url: user_url, html: { class: "col col-md-4" }) do |f| %>
  <div class="row gap-4 align-content-center">
    <%= f.text_field(:username, required: true, class: "form-control col-12", placeholder: "Username") %>
    <%= f.email_field(:email, required: true, class: "form-control col-12", placeholder: "Email address") %>
    <%= f.password_field(:password, required: true, class: "form-control col-12", placeholder: "Password") %>
    <%= f.password_field(:password_confirmation, required: true, class: "form-control col-12", placeholder: "Confirm password") %>
    <%= f.button("Sign up", class: "btn btn-primary col-6") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#edit</h1>
  <p>Find me in app/views/users/edit.html.erb</p>
</div>

app/views/users/new.html.erb
<div class="row justify-content-center">
  <%= render "form" %>
</div>

app/views/users/show.html.erb
<div>
  <h1 class="font-bold text-4xl"><%= current_user.username %></h1>
  <p>Find me in app/views/users/show.html.erb</p>
</div>