config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get '_up' => 'rails/health#show', as: :rails_health_check

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resource :collection, only: %i[show]
  resource :session, only: %i[new create destroy]
  resource :user

  namespace :pokemon do
    resources :cards, only: %i[index show]
  end

  # Defines the root path route ("/")
  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deckshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg border-bottom">
      <div class="container-fluid">
        <%= link_to("Deckshare", root_url, class: "navbar-brand") %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <% if current_user? %>
              <li class="nav-item dropdown">
                <%= link_to(current_user, "#", class: "nav-link dropdown-toggle", role: "button", "data-bs-toggle": "dropdown", "aria-expanded": "false") %>
                <ul class="dropdown-menu dropdown-menu-end">
                  <li><%= link_to("My Collection", collection_path, class: "dropdown-item") %></li>
                  <li><%= link_to("Settings", user_path, class: "dropdown-item") %></li>
                  <li><%= link_to("Log out", session_path, class: "dropdown-item", "data-turbo-method": :delete) %></li>
                </ul>
              </li>
            <% else %>
              <li class="nav-item"><%= link_to("Log in", new_session_path, class: "nav-link") %></li>
              <li class="nav-item"><%= link_to("Sign up", new_user_path, class: "nav-link") %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <main class="container my-4">
      <%= yield %>
    </main>
  </body>
</html>